### ISSUE TITLE
Error on adding new member

### ISSUE THREAD

**Issue by OstapW** [synmetrix/synmetrix#129]
Hi

I have a clean installation of synmetrix with email settings(SMTP_*). 
I try to add new member but when I push invite I get an error
[GraphQL] Sending magic link failed. Check your SMTP settings

I see env vars SMTP_* inside of stack container, I double check settings that I'm able to connect to smtp server.
In logs I see error below:
::ffff:127.0.0.1 - - [27/Sep/2024:10:00:50 +0000] "POST /auth/register HTTP/1.1" 200 518
TypeError: Cannot set property errored of #<Readable> which has only a getter
    at new MessageSplitter (/app/stack/services/hasura-backend-plus/node_modules/mailsplit/lib/message-splitter.js:28:22)
    at new MailParser (/app/stack/services/hasura-backend-plus/node_modules/mailparser/lib/mail-parser.js:132:25)
    at module.exports (/app/stack/services/hasura-backend-plus/node_modules/mailparser/lib/simple-parser.js:25:18)
    at previewEmail (/app/stack/services/hasura-backend-plus/node_modules/preview-email/lib/index.js:56:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Email.send (/app/stack/services/hasura-backend-plus/node_modules/email-templates/lib/index.js:279:98)
    at async loginAccount (/app/stack/services/hasura-backend-plus/dist/routes/auth/login.js:71:13)
::ffff:127.0.0.1 - - [27/Sep/2024:10:00:50 +0000] "POST /auth/login HTTP/1.1" 500 96
{"level":50,"time":1727431250267,"pid":329,"hostname":"stack-0","msg":{"name":"MagicLinkError"}}

**Comment by ifokeev** [comment]
Hi @OstapW! Looks like a bug in the hasura-backend-plus `mailsplit` version https://github.com/nhost/hasura-backend-plus/blob/master/yarn.lock#L9065, this PR fixed the error https://github.com/andris9/mailsplit/pull/16/files.

But I think you have this problem because your SMTP connection is not correct. You need to provide SMTP env variables according to this doc https://github.com/nhost/hasura-backend-plus/blob/2713d00ddf8480d2ff66cb83f22af8170b142edd/docs/docs/environment-variables.md?plain=1#L213
